#ifndef EOS_INTERPOLATOR_H
#define EOS_INTERPOLATOR_H

#include <filesystem>
#include <iostream>
#include <cmath>
#include <vector>

#include <Kokkos_Core.hpp>
#include <Cabana_Core.hpp>

#include "H5Cpp.h"

#include "utilities.h"
#include "particle.h"
#include "thermodynamic_info.h"


namespace fs = std::filesystem;

/// @brief Class for interpolating the EoS table
/// Assumes that the EoS table is in the format:
/// The first 4 lines are headers, containing the limits of the grid in each dimension
/// There is a 5th header line with the names of the variables
/// The rest of the lines are space separated values of the variables
/// The table has as independent variables: s, rhoB, rhoQ, rhoS. These are laid
/// out in a regular grid. The slowest changing variable is rhoS, followed by rhoQ,
/// followed by rhoB, followed by s.

namespace ccake {

using eos_thermo = Kokkos::View<const double****, DeviceType, Kokkos::MemoryTraits<Kokkos::RandomAccess>>;
using eos_thermo_nonconst = Kokkos::View<double****, DeviceType>;
using eos_thermo_kind = Kokkos::View<const int****, DeviceType, Kokkos::MemoryTraits<Kokkos::RandomAccess>>;

namespace eos_variables{
enum eos_variables_enum{
  T, muB, muQ, muS,
  e, p, cs2,
  dw_ds, dw_dB, dw_dQ, dw_dS,
  NUM_EOS_VARIABLES
  };
}

#define NTBL_s 5
#define NTBL_B 4
#define NTBL_S 4
#define NTBL_Q 4

/// @class EoS_Interpolator
/// @brief Class for interpolating the EoS table
/// @details This class reads an EoS table from a HDF5 file generated by the
/// EOS table generator (see utilities folder). The file contains many groups
/// named table_s_B_S_Q, where s, B, S, and Q denotes the values of the powers
/// of the corresponding thermodynamic variables. For example, table_0_-1_-2_0
/// contains the values of the thermodynamic variables at
/// \f$ s \in [1.000,10.000]\f$, \f$ B \in [0.100,1.000]\f$,
/// \f$ S \in [0.010,0.100]\f$ and \f$ Q \in [1.000,10.000]\f$. Values smaller
/// than 1.E-3 are considered rounded to 1.E-3. All values are in fm\f$^{-3}.
/// Metadata is stored in the attributes of the groups and contains the minimum,
/// maximum, step and number of points in each dimension. We also assume
/// symmetry in the directions of B, S, and Q, so we only store the values for
/// B>0, S>0, and Q>0.
class EoS_Interpolator{

private:
  eos_thermo_nonconst eos_vars[NTBL_s][NTBL_B]
                              [NTBL_S][NTBL_Q]
                              [eos_variables::NUM_EOS_VARIABLES]; ///< Stores the values of the EoS tables
  //HDF5 file
  H5::H5File eos_file; ///< HDF5 file containing the EoS tables

  /// @brief Struct to hold the attributes of the EoS tables
  /// @details This struct holds the minimum, maximum, step and number of points
  /// in each dimension of the EoS tables. When `log_spacing` is true the stored
  /// `min`, `max`, `step` are interpreted as log10 of the physical value, and
  /// the interpolator transforms query coordinates with log10 before computing
  /// indices. Used by the flat (s, nB) format which spans many decades.
  struct table_attributes{
    double min, max, step;
    int N;
    bool log_spacing = false;
  };

  table_attributes s_attr[NTBL_s][NTBL_B][NTBL_S][NTBL_Q],
                   B_attr[NTBL_s][NTBL_B][NTBL_S][NTBL_Q],
                   S_attr[NTBL_s][NTBL_B][NTBL_S][NTBL_Q],
                   Q_attr[NTBL_s][NTBL_B][NTBL_S][NTBL_Q]; ///< Attributes of each direction for each EoS tables


  void load_table(std::initializer_list<int> exponents);
  void load_header(std::initializer_list<int> exponents);

  /// @brief Load a "flat" (s, nB) pre-inverted EoS table.
  /// @details Reads the alternative HDF5 layout (root `/dimensions` + per-field
  /// 2D datasets under `/data/`) into slot [0][0][0][0] with degenerate S, Q
  /// axes and log_spacing on the s, nB axes. Computes dwds/dwdB analytically
  /// from chiTT/chiTB/chiBB using the baryon-only Schur complement that mirrors
  /// EquationOfState::dwds/dwdB. dwdS = dwdQ = 0.
  void load_flat_table();

  /// True when the file passed to the constructor is in the flat (s, nB)
  /// per-field-dataset format. Selects the simplified codepath in
  /// fill_thermodynamics (skip per-decade tile lookup; apply log10 transform on
  /// log-spaced axes).
  bool is_flat_ = false;

  // -------- Host-side mirrors of the flat table (populated only in flat mode).
  // Used by query_thermo_host / invert_e_to_s_host / efreeze_at_T to service
  // the IC initialization and the freeze-out energy lookup on the CPU without
  // needing to touch the forward EoS or the device-side Kokkos Views.
  std::vector<double> flat_T_, flat_muB_, flat_muS_, flat_muQ_;
  std::vector<double> flat_e_, flat_p_, flat_cs2_;
  std::vector<double> flat_dwds_, flat_dwdB_;
  std::vector<double> flat_s_axis_, flat_nB_axis_;  // physical, fm⁻³
  int    flat_Ns_      = 0;
  int    flat_NB_      = 0;
  double flat_log_s_min_  = 0.0;
  double flat_dlog_s_     = 0.0;
  double flat_log_nB_min_ = 0.0;
  double flat_dlog_nB_    = 0.0;

  inline size_t flat_idx(int is, int iB) const {
    return static_cast<size_t>(is) * flat_NB_ + iB;
  }

public:
  /// True when the loaded file is the flat (s, nB) per-field-dataset format.
  bool is_flat() const { return is_flat_; }

  /// Host-side query at (s, rhoB) in fm⁻³. Returns false if out of table range.
  /// Strangeness/electric sectors are populated with the table's stored muS,
  /// muQ (= 0 for the user's neutral-flavor table) and rhoS = rhoQ = 0.
  /// Flat-mode only — calling on a tiled-format file will return false.
  bool query_thermo_host(double s, double rhoB, thermodynamic_info & out) const;

  /// Host-side e → s inversion at fixed rhoB. Bisects on the s axis (where e is
  /// monotone increasing for QGP-like EoS), then populates `out` via
  /// query_thermo_host at the recovered (s, rhoB). Returns false if rhoB is
  /// below the table's nB axis. Inputs in fm-natural units.
  bool invert_e_to_s_host(double e_input, double rhoB, thermodynamic_info & out) const;

  /// Host-side freeze-out energy density at temperature T (fm⁻¹).
  /// Scans the smallest-nB column of the table for the cell where T_table
  /// crosses T_fm and returns the corresponding e (fm⁻⁴).
  double efreeze_at_T(double T_fm) const;

  KOKKOS_FUNCTION
  double interpolate1D(double x, double x0, double x1,
                                 double y0, double y1) const;

  KOKKOS_FUNCTION
  double interpolate4D(int idx[], double pos[], int tble[], int ivar) const;
  KOKKOS_FUNCTION
  double interpolate4D_slow(int idx[], double pos[], int ivar) const;


public:
  EoS_Interpolator() = delete;
  EoS_Interpolator(fs::path path_to_eos_table);
  ~EoS_Interpolator() = default;

  void fill_thermodynamics(Cabana::AoSoA<CabanaParticle, DeviceType, VECTOR_LENGTH> &particles, const double t);

};

} // namespace ccake
#endif